version: "3.9"

services:
  web:
    image: drupal:e7370dc00250
    ports:
      - "80:80"
    volumes:
      - ./drupal:/var/www/html
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_USER: admin
      DRUPAL_DB_PASSWORD: admin
      DRUPAL_DB_NAME: drupal

  db:
    image: mysql:8.2.0
    volumes:
      - drupal-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: drupal